# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor1 = torch.rand(size=(7,7))

random_tensor1

tensor([[0.5626, 0.7058, 0.3488, 0.2900, 0.9318, 0.1521, 0.0980],
        [0.7895, 0.9116, 0.8780, 0.4301, 0.2603, 0.0400, 0.7771],
        [0.8927, 0.2681, 0.0159, 0.4053, 0.9758, 0.6121, 0.3831],
        [0.2094, 0.1131, 0.9224, 0.5414, 0.3196, 0.1573, 0.1325],
        [0.9738, 0.0961, 0.5376, 0.9442, 0.5156, 0.7382, 0.7828],
        [0.0772, 0.0110, 0.4281, 0.3501, 0.4831, 0.8713, 0.4761],
        [0.1403, 0.3762, 0.2121, 0.4556, 0.8372, 0.0065, 0.7098]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor2 = torch.rand(size=(1,7))
# Perform matrix multiplication
random_tensor2

tensor_mult = torch.matmul(random_tensor1, random_tensor2.T)

tensor_mult, tensor_mult.shape

(tensor([[1.6959],
         [2.4210],
         [2.2717],
         [1.2610],
         [2.9725],
         [1.7143],
         [1.3193]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
MANUAL_SEED = 0

torch.manual_seed(MANUAL_SEED)

# Create two random tensors
random_tensor3 = torch.rand(7, 7)
random_tensor4 = torch.rand(1, 7)

# Matrix multiply tensors
tensor_mult2 = torch.matmul(random_tensor3, random_tensor4.T)

tensor_mult2

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
randGPUTensor1 = torch.rand(size=(2,3)).to(device)
randGPUTensor2 = torch.rand(size=(2,3)).to(device)

randGPUTensor1, randGPUTensor2

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
tensorMult = torch.matmul(randGPUTensor1, randGPUTensor2.T)

tensorMult, tensor_mult.device, tensorMult.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 device(type='cpu'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [34]:
# Find max
maxValue = tensorMult.max()

# Find min
minValue = tensorMult.min()

maxValue, minValue

print("Does this give the same result? Let's see...\n")
if maxValue == torch.max(tensorMult) and minValue == torch.min(tensorMult):
    print(f"Yes! {maxValue} is equal to {torch.max(tensorMult)} and {minValue} is equal to {torch.min(tensorMult)} !")
else:
    print("NO!")


Does this give the same result? Let's see...

Yes! 0.5617256760597229 is equal to 0.5617256760597229 and 0.3647301495075226 is equal to 0.3647301495075226 !


### 9. Find the maximum and minimum index values of the output of 7.

In [39]:
# Find arg max
maxIndexValue = torch.argmax(tensorMult)
maxIndexValue2 = tensorMult.argmax()

# Find arg min
minIndexValue = torch.argmin(tensorMult)
minIndexValue2 = tensorMult.argmin()

maxIndexValue, minIndexValue, maxIndexValue2, minIndexValue2, maxIndexValue == maxIndexValue2, minIndexValue == minIndexValue2

(tensor(3), tensor(0), tensor(3), tensor(0), tensor(True), tensor(True))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor10 = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor10Squeezed = tensor10.squeeze()

# Print out tensors and their shapes
print(tensor10, tensor10.shape)
print(tensor10Squeezed, tensor10Squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
